In [58]:
#PART1

In [59]:
import pandas as pd
import torch
import numpy as np

In [66]:
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
train_df

POS_0_9_CP  POS_10_19_CP  POS_20_29_CP  POS_30_39_CP  POS_40_49_CP  \
0             24            51            44            51            60   
1             22            31           214           177            62   
2             84           126           239           194           159   
3             65            76            80           110            82   
4             99           107           339           287           139   
...          ...           ...           ...           ...           ...   
1039          86           201           206           202           240   
1040          80           102           125           124           104   
1041         268           358           277           415           355   
1042          81           116            90           145           118   
1043         118           156           197           215           114   

      POS_50_59_CP  POS_60_69_CP  POS_70_79_CP  POS_80_89_CP  POS_90_CP  \
0               75            72            61            27          0   
1               46            24             9             0          0   
2              171           125            74            24          8   
3               81            55            49            56         34   
4              147           110            71            37          0   
...            ...           ...           ...           ...        ...   
1039           317           225           138            48          0   
1040            71            70            36             6          0   
1041           332           215           107            47          7   
1042           113            70            36             9          0   
1043           114            83            19             0          0   

      DTH_CUM_CP  
0              3  
1              2  
2              9  
3              7  
4             12  
...          ...  
1039           7  
1040           6  
1041           5  
1042           2  
1043           5  

[1044 rows x 11 columns]

In [63]:
trainX = torch.from_numpy(train_df.values[:,:-1]).to(torch.float64)
trainY = torch.from_numpy(train_df.values[:,-1:]).to(torch.float64)

testX = torch.from_numpy(test_df.values[:,:-1]).to(torch.float64)
testY = torch.from_numpy(test_df.values[:,-1:]).to(torch.float64)
trainX

tensor([[ 24.,  51.,  44.,  ...,  61.,  27.,   0.],
        [ 22.,  31., 214.,  ...,   9.,   0.,   0.],
        [ 84., 126., 239.,  ...,  74.,  24.,   8.],
        ...,
        [268., 358., 277.,  ..., 107.,  47.,   7.],
        [ 81., 116.,  90.,  ...,  36.,   9.,   0.],
        [118., 156., 197.,  ...,  19.,   0.,   0.]], dtype=torch.float64)

In [64]:
trainY

tensor([[3.],
        [2.],
        [9.],
        ...,
        [5.],
        [2.],
        [5.]], dtype=torch.float64)

In [67]:
coef = torch.tensor([
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0040], # POS_50_59_CP
        [0.0300], # POS_60_69_CP
        [0.0300],
        [0.0300],
        [0.0300]
], dtype=testX.dtype)
coef

tensor([[0.0040],
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0040],
        [0.0300],
        [0.0300],
        [0.0300],
        [0.0300]], dtype=torch.float64)

In [75]:
(testX[:1,:]@coef).item()

float

In [69]:
torch.cuda.is_available()

False

In [70]:
#Part2

In [117]:
predictedY = (testX[:,:]@coef)
predictedY

In [121]:
def r2_score(trueY, predictedY):
    SStot = torch.sum(pow((testY-torch.mean(testY)),2))
    SSreg = torch.sum(pow((testY-predictedY),2))
    improvement = SStot - SSreg
    R2_score = improvement/SStot
    return R2_score

In [123]:
print(r2_score(testY, predictedY))

tensor(0.4110, dtype=torch.float64)
